- platformthemeplugin/dthemesettings.cpp
- platformthemeplugin/dthemesettings.h
- platformthemeplugin/qdeepintheme.cpp
- platformthemeplugin/qdeepintheme.h
> feat: screen scale support takes effect in real time

- platformthemeplugin/qdeepintheme.cpp
Without the fix qdeepin platformtheme failed to load:
```
Cannot load library /usr/lib/qt/plugins/platformthemes/libqdeepin.so: (/usr/lib/qt/plugins/platformthemes/libqdeepin.so: undefined symbol: _ZN15QHighDpiScaling12m_logicalDpiE)
```
> fix: qt 5.14 compatibility issues

- .packit.yaml
- rpm/deepin-qt5integration.spec
This commit contains the specfile for building the official package for Fedora
with a Packit setup.
Ultimately, a unified specfile is targeted for Fedora and any other rpm-based
distributions, e.g. openEuler.
And Packit(https://packit.dev/) is a tool for maintaining specfile within
upstream source. It requires a simple config file(.packit.yaml).
Log: Initial packit setup
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
> feat: Initial packit setup

- rpm/deepin-qt5integration.spec
Fedora no longer installs make in the default build environment.
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
> fix: rpm BuildRequires make

- styleplugins/chameleon/chameleonstyle.cpp
社区版窗口圆角可以改变，不应该给菜单固定大小的圆角
此处从主题中获取圆角大小，但是最大不超过8（和以前保持一致）
Log: 菜单圆角保持一直
Influence: 菜单圆角
Change-Id: Idc86c46e3eabff070e0a9d635ceee81c6bbf6bd3
> chore: 菜单圆角跟随控制中心圆角变化

- styleplugins/chameleon/chameleonstyle.cpp
当设置menu圆角时候，增加wayland条件判断
Log: 修复工具栏二级菜单界面未做圆角处理问题
Bug: https://pms.uniontech.com/bug-view-101126.html
Influence: 二级菜单圆角
> fix: wayland 菜单界面未做圆角处理

- styleplugins/chameleon/chameleonstyle.cpp
绘制combobox时增加调色板变化判断。
调色板变化时，设置画刷为palette.button。
Log: 修复警告提示时，combobox输入框背景色无变化问题
Bug: https://pms.uniontech.com/bug-view-128179.html
Influence: 可编辑combobox样式
> fix: 警告提示时，combobox输入框背景色无变化

- styleplugins/chameleon/chameleonstyle.cpp
combobox弹出菜单计算时未加上图片的宽度导致图片和文字重叠
Log:
Bug:
Change-Id: I05ebe21d0ce72250450884ce31005fb8a368f301
> fix: combobox弹出菜单文字和图片重叠

- styleplugins/chameleon/chameleonstyle.cpp
1、只有DTK应用日历的窗口才绘制圆角
2、周末背景高亮跟随放在polish处理
Log: 修复非DTk应用的日历窗口绘制圆角问题
Influence: 日历窗口圆角和周末高亮
> fix: 非DTK应用的日历窗口绘制了圆角

- styleplugins/chameleon/chameleonstyle.cpp
取得宽度是整个文字内容的宽度，
修改为可以绘制文字的区域宽度。
Log: 修复带图标combobox文字过长未省略问题
Bug: https://pms.uniontech.com/bug-view-135023.html
Influence: DCombobox显示
> fix: 带图标的combobox文字过长未省略

- styleplugins/chameleon/chameleonstyle.cpp
we add QScrollArea's handler flowing QAbstractItemView,
for MouseEvent and QContextMenuEvent, we distribute event for
it's child widget in the position when scrollbar in hide state.
Log: QScrollArea中QScrollBar的点击事件被拦截
Bug: https://pms.uniontech.com/bug-view-132675.html
Influence: 所有使用了ListView和及QScrollArea的应用
Change-Id: Ib4f95826402213e04000eb5aecd536f37ee7b8e8
> fix: MouseEvent intercepted in QScrollArea's scrollbar

- styleplugins/chameleon/chameleonstyle.cpp
add null pointer judge when `childAt()` return a empty child.
Log: 
Change-Id: I961bfb58f269bcd895856f5c262ebae01e5db473
> fix: Access null pointer for QScrollArea

- styleplugins/chameleon/chameleonstyle.cpp
combobox在可编辑状态下，背景色取lineEdit的调色板button的颜色
Log: 修复combobox警告提示时没有警告背景色问题
Bug: https://pms.uniontech.com/bug-view-128179.html
Influence: combobox背景色
> fix: 可编辑的combobox警告提示时没有警告背景色

- platformthemeplugin/qdeepinfiledialoghelper.cpp
- platformthemeplugin/qdeepinfiledialoghelper.h
- platformthemeplugin/qt5deepintheme-plugin.pro
- src/platformthemes/platformthemechooser/platformthemechooser.pro
1. 主题插件移除qt5widget5的依赖(QT += widgets widgets-privat)
2. 重命名变量 nativedialog -> filedlgInterface
Log: remove depends
Influence: filedialog
Change-Id: Ie95a1b663524bddeb1c6777d510e642b24e9ee23
> chore: remove qt5widget5 depends from themeplugin

- styleplugins/chameleon/chameleonstyle.cpp
修改为PM_SubMenuOverlap的pixelMetric返回0
Log: 修复主菜单和子菜单边框重叠显示问题
Bug: https://pms.uniontech.com/bug-view-134533.html
Influence: 主菜单和子菜单UI
> fix: 主窗口和子菜单窗口边框重叠显示

- qt5integration.pro
上游不需要 BASED_DTK_DIR 宏来生成chooser插件，避免上游生成两个包
Log:
Change-Id: I3d565ee9b1f28c1a88b969e5693072979455ac11
> chore: 没有设置 BASED_DTK_DIR 时不生成chooser相关的库

- debian/control
dde-qt5integration5.5 was deprecated
Log: 升级时卸载dde-qt5integration5.5
Bug: https://pms.uniontech.com/bug-view-138883.html
Influence: dtk5.5
Change-Id: I0e785380e0c6cfa957c7893d5b071a1b148e1929
> chore: replace dde-qt5integration5.5

- styleplugins/chameleon/chameleonstyle.cpp
计算菜单项文本的位置时，
多加了smallIconSize距离。
Log: 菜单项图标和文本的距离减少smallIconSize
Bug: https://pms.uniontech.com/bug-view-140633.html
Influence: 弹出菜单
Change-Id: I4e0bdfda7f24833450a746cc117bc76bd6a00ad4
> fix: 减小菜单项图标和文本的距离

- platformthemeplugin/qdeepintheme.cpp
支持可配置所使用的代理 Qt 图标引擎
当前 qdeepintheme 所自动选用的是其附带的图标引擎，此图标引擎在部分（至少在 Arch Linux）平台存在一些渲染问题，例如无法正常渲染 SVG 1.2 Tiny 之外的图标（如现在发布时提供的 `deepin-image-viewer` 图标），或是包含 `ColorScheme-Text` 之外颜色定义的图标（如 KDE breeze-icon-theme 中的 folder 图标，使用了 `ColorScheme-Highlight`）。
比较快捷的 workaround 即使 qdeepintheme 所创建的图标引擎可配置而非 hardcode 到指定图标引擎，此 PR 在现有的配置文件`~/.config/deepin/qt-theme.ini` 中，追加了一个配置项 `ProxyIconEngineName`，允许通过指定图标引擎的名称来使 deepin 主题使用给定的图标引擎。
当然上述问题也应当考虑在 deepin 所提供的图标引擎中进行修复。
> feat: configurable proxy icon engine

- styleplugins/chameleon/chameleonstyle.cpp
可编辑combobox设置个默认背景色，
如果有设置警告，则以警告对象的调色板button为背景色。
Log: 修复可编辑的combobox没有背景色问题
Bug: https://pms.uniontech.com/bug-view-146359.html
Influence: combobox
Change-Id: I74883c52a4c237280683f487830b5ec5ddd20e38
> fix: 可编辑的combobox没有背景色

- iconengineplugins/builtinengine/dbuiltiniconengine.cpp
- iconengineplugins/svgiconengine/qsvgiconengine.cpp
- iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
较大的图标（如1024x1024）的 png 图片在缩放（如2）时出现图标模糊
因为绘制时获取的 pixmap 的 size 未乘以缩放值
Log: 
Change-Id: I650fbb3886464067ba8a5086d9e5ff2373dfabd7
> fix: png高清图片在缩放时模糊的问题

- iconengineplugins/builtinengine/dbuiltiniconengine.cpp
- iconengineplugins/svgiconengine/qsvgiconengine.cpp
- iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
较大的图标（如1024x1024）的 pixmap 在缩放（如2）时出现图标模糊
因为绘制时获取的 pixmap 的 size 未乘以缩放值
Bug: https://pms.uniontech.com/bug-view-154115.html
Log: 图标模糊
Change-Id: I650fbb3886464067ba8a5086d9e5ff2373dfabd7
> fix: iconengine 缩放后绘制 pixmap 问题

- iconengineplugins/dciiconengine/dciiconengine.cpp
use dynamic_cast instead of reinterpret_cast
Log: crash when use dciiconengine
Bug: none
Influecen: none
> fix crash && icon intercepted

- iconengineplugins/dciiconengine/dciiconengine.cpp
- iconengineplugins/dciiconengine/dciiconengine.h
icon not changed whene switch dci icon theme
check icon theme name in dciiconengine
Log: fix dci icon not changed
Influence: dci icon theme
Change-Id: Ie8adbf6d31abff9152c7f1a381b23834a59a3802
> fix: dci icon not changed

- styleplugins/chameleon/chameleonstyle.cpp
forcus rect radius is bigger than border radius
Bug: https://pms.uniontech.com/bug-view-179601.html
Log: focus rect
Change-Id: I592193b14c2c1eb5057e1937969e84bddaad80b2
> fix: focus rect not covering corners

- iconengineplugins/diconproxyengine/diconproxyengine.cpp
add non_cache to aviod frequently create icon engine when an icon name not fround in all themes(builtin/dci/xdg) Note that there is a risk of not being able to update the cache in time when new icons are installed and app not restarted
Log: theme icon cache
Influence: icon cache
Change-Id: Idffeb6b647019e43c3579ac69eea9a4cb37c9fa2
> chore: add noncache avoid frequently create engine

- iconengineplugins/diconproxyengine/diconproxyengine.cpp
- platformthemeplugin/qdeepintheme.cpp
if proxy iconengine is null, virtual_hook return
QIconEngine::virtual_hook, by default QIconEngine::isNull return false
Log: none
Influence: qicon.isNull reuturn false
Change-Id: I0b656b3e759006056a12bd74d5dacdff44880f80
> fix: qicon::isNull always return false

- platformthemeplugin/qdeepinfiledialoghelper.cpp
Invoking QFileDialog::close() will not quit local eventloop started by
QDeepinFileDialogHelper::exec(). Connect destroyed signal to quit slot of
local eventloop to fix this. Notice that user should destroy QFileDialog
to quit local eventloop.
Log: fix eventloop quit error
Bug: https://pms.uniontech.com/bug-view-183603.html
> fix: local eventloop won't after manually close

- iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
- iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.h
对 ColorScheme-Highlight 非常初步的支持，尽管仍未支持 ColorScheme-Background。
此 patch 可解决 breeze 主题下，文件夹图标显示为黑色的问题。
测试方式：
1. 构建插件
2. 在较新的环境下，安装并切换默认主题到 breeze（deepin v20 可能不够新，建议使用 Arch，另，下述涉及的文件对应到[这个](https://github.com/KDE/breeze-icons/blob/master/icons/places/64/folder.svg)）
3. 获取并构建 https://github.com/BLumia/qt-icon-engine-tool （方便起见提供此工具）
4. 清空图标缓存（缓存位于 `~/.cache/deepin/icons`）
5. 使用 `QT_PLUGIN_PATH=/path/to/qt5integration/bin/plugins/` 启动上面构建得到的 `iconenginelist` 程序，并在下拉中选择 “DIconProxyEngine”
6. 观察效果，颜色非黑色即正常
此 patch 已知问题：
1. 切换当前主题色时不会清除缓存，所以会看到首次生成缓存时的图标。
> feat: basic support for ColorScheme-Highlight

- styleplugins/chameleon/chameleonstyle.cpp
set scrollbar policy with xsettings `Qt/ScrollBarPolicy` same as Qt::ScrollBarPolicy
0 show as needed auto hide, default
1 always off
2 always on
Task: https://pms.uniontech.com/task-view-240117.html
Log: scrollbar policy
Change-Id: Id7c2beae069b7cf419df4b326bbda49f103aaa76
> feat: scrollbar policy support xsettings control

- iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
- iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.h
file-manager is crashed due to colorScheme variable's naming conflict (xdgiconproxyengine.cpp & qdeepintheme.cpp)
Log: resolve the issue which file-manager is crashed in live-system
Bug: https://pms.uniontech.com/bug-view-188633.html
Influence: icon engine plugin
> fix: file-manager is crashed when loading xdgiconproxyengine

- styleplugins/chameleon/chameleonstyle.cpp
Indicator had different calculation for between up with
down, it causes that indicator display different.
Issue: https://github.com/linuxdeepin/developer-center/issues/3674
> fix: Calculating size different for SpinBox up and down

- styleplugins/chameleon/chameleonstyle.cpp
Adjust toolbar sizeHint to 36 in NormalMode.
Adjust toolbar sizeHint to 24 in CompactMode.
Issue: https://github.com/linuxdeepin/dtkwidget/issues/326
> fix: Modify size style for toolbar

- styleplugins/chameleon/chameleonstyle.cpp
In design, PushButton's height is 36 in NormalMode
and it is 24 in Compact, the margin of Arrow with frame is 10.
We only minus `ButtonMargin` for height to adap CompactMode,
and use `ButtonMargin` as Arrow's margin, And `PM_ButtonMinimizedSize` is 36, so we don't worry it is smally.
Issue: https://github.com/linuxdeepin/dtkwidget/issues/326
> fix: Modify PushButton's size to Adapt Compact

- styleplugins/chameleon/chameleonstyle.cpp
when style is changed, set SH_ComboBox_PopupFrameStyle to the origin frameShape
Log: black border in combobox's popup window
Issue: https://github.com/linuxdeepin/developer-center/issues/3914
Influence: QFrame style
> fix: black border in combobox's popup window

- iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
QIcon::pixmap will scaled with ratio
use qicon.engine->pixmap instead of qicon::pixmap
Fix-Bug-185279
Log:
> fix: icon size multiplied by ratio twice

- styleplugins/chameleon/chameleonstyle.cpp
PE_PanelItemViewItem is fill background using backgroundBrash
if backgroundBrush isn't NoBrush, we use drawRounded in this scene.
Issue: https://github.com/linuxdeepin/dtkwidget/issues/399
> fix: DStandardItem hasn't radius

- platformthemeplugin/deepin.json
- platformthemeplugin/main.cpp
> chore: deepin theme plugin add DDE key

- styleplugins/chameleon/chameleonstyle.cpp
菜单窗口只是在 polish 时设置了圆角。
主窗口的菜单关闭后并不会销毁，只是隐藏了
如果隐藏后窗口圆角变化并不会跟随
Issue: https://github.com/linuxdeepin/dtkwidget/issues/409
> fix: menu window radius not update

- iconengineplugins/dciiconengine/dciiconengine.cpp
QIcon::pixmap 已经乘以了一次缩放，所以 iconengine
无需在乘以一次缩放，否则容易导致图标变的更大
Issue: https://github.com/linuxdeepin/developer-center/issues/4077
> fix: dci icon pixmap scaled again

- styleplugins/chameleon/chameleonstyle.cpp
修复 https://github.com/linuxdeepin/dtk/issues/31 后 edit 在设置过透明的窗口中自带透明背景色
此提交并不能直接修复这个问题.需要应用设置属性
edit->setProperty("_d_dtk_lineedit_opacity", false); // 禁止edit透明背景
Issue: https://github.com/linuxdeepin/developer-center/issues/4069
Bug: https://pms.uniontech.com/bug-view-196961.html
> fix: edit translucent background

- platformthemeplugin/qdeepintheme.cpp
Theme font should not be cached as dpi may change. We need to create a new font and refresh font dpi.
Log: fix refresh font dpi
Issue: https://github.com/linuxdeepin/dtk/issues/17
> fix: refresh font dpi

- platformthemeplugin/qdeepinfiledialoghelper.cpp
- platformthemeplugin/qdeepinfiledialoghelper.h
When QFileDialog invokes deleteLater or close, event loop doesn't quit normally because of lacking notification from Qt. Just store local event loop and quit it if running in hide(). Cause hide() will be invoked by Qt when close.
Log: fix event loop doesn't quit normally
> fix: event loop doesn't quit normally

- iconengineplugins/dciiconengine/dciiconengine.cpp
pixmap key associated with dci icon pixmap params
Fix too much pixmap cache
> chore: pixmap cache key tweak

- debian/rules
Always use qmake to keep stable when refactor to cmake.
> chore: always use qmake

- CMakeLists.txt
- iconengineplugins/CMakeLists.txt
- iconengineplugins/builtinengine/CMakeLists.txt
- iconengineplugins/builtinengine/dbuiltiniconengine.cpp
- iconengineplugins/builtinengine/dbuiltiniconengine.h
- iconengineplugins/dciiconengine/CMakeLists.txt
- iconengineplugins/dciiconengine/dciiconengine.cpp
- iconengineplugins/dciiconengine/dciiconengine.h
- iconengineplugins/diconproxyengine/CMakeLists.txt
- iconengineplugins/diconproxyengine/diconproxyengine.cpp
- iconengineplugins/diconproxyengine/diconproxyengine.h
- iconengineplugins/svgiconengine/CMakeLists.txt
- iconengineplugins/svgiconengine/qsvgiconengine.cpp
- iconengineplugins/xdgiconproxyengine/CMakeLists.txt
- iconengineplugins/xdgiconproxyengine/main.cpp
- iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.cpp
- iconengineplugins/xdgiconproxyengine/xdgiconproxyengine.h
* iconengines now support building using cmake
* iconengines support building under Qt6
Log: support cmake and Qt6
> feat: support cmake and Qt6

- CMakeLists.txt
- imageformatplugins/CMakeLists.txt
- imageformatplugins/dci/CMakeLists.txt
- imageformatplugins/svg/CMakeLists.txt
- imageformatplugins/svg/main.cpp
imageformatplugins now support building under Qt6 and using cmake.
Log: imageformatplugins support cmake and Qt6
> feat: imageformatplugins support cmake and Qt6

- styleplugins/chameleon/chameleonstyle.cpp
if we set palette to lineedit on dialog(transluent background) use the color we set instead of trans bg color
Issue: https://github.com/linuxdeepin/dtk/issues/91
> fix: DLineEdit setAlert not work on DDialog

- 3rdparty/qdbustrayicon.cpp
- 3rdparty/qdbustrayicon_p.h
- platformthemeplugin/CMakeLists.txt
3rdparty sources are missing thus some symbols cannot be found and libqdeepin.so loading failed. Icon and action resources are also missing. Add them and adapt to Qt6.
Log: fix missing 3rdparty sources and resources
> fix: missing 3rdparty sources and resources

- iconengineplugins/svgiconengine/qsvgiconengine.cpp
QtConcurrent::run is marked nodiscard. Implicitly discard its return value using maybe_unused.
Log: fix nodiscard warning
> chore: fix nodiscard warning

- CMakeLists.txt
- styleplugins/CMakeLists.txt
- styleplugins/dstyleplugin/CMakeLists.txt
If ENABLE_OLD_STYLE is not ON manually, dstyleplugin will not be compiled. And it will never be installed even if compiled.
Log: fix do not compile and install dstyleplugin
> fix: do not compile and install dstyleplugin

- styleplugins/chameleon/chameleonstyle.cpp
It introduced in ff4669f1df5bfc61617b9bdb1d67084cb822d7fd,
and remove it depend on UI designer.
Issue: https://github.com/linuxdeepin/dtk/issues/73
> fix: The size of the ListView item's rect is incorrect

- platformthemeplugin/CMakeLists.txt
- platformthemeplugin/qdeepintheme.cpp
- platformthemeplugin/qdeepintheme.h
Dbusmenu related symbols are hidden in Qt6 now, we just can't partially customize it. Either fully override it (Do not depend any symbol in QtGui) or just leave it default. Cause we just make a little customization, just leave it default in Qt6 and try to contribute our improvement to upstream.
Related-Commit: 78fa103aadf39f19b3f613647a7d3931b4b27e57
Log: fix dbusmenu related symbols are hidden in Qt6
> fix: dbusmenu related symbols are hidden in Qt6

- iconengineplugins/dciiconengine/dciiconengine.cpp
dci 图标缓存没有加上主题名导致可能在不同的主题时匹配到其他主题缓存的图标
Issue: https://github.com/linuxdeepin/developer-center/issues/4517
> fix: dci icon cache key miss theme name

- styleplugins/chameleon/chameleonstyle.cpp
We use button as background when unset brush, and it also takes
effect when hover.
Issue: https://github.com/linuxdeepin/dtk/issues/61
> fix: Combobox's background is wrong when hover

- .reuse/dep5
- tests/CMakeLists.txt
- tests/styleplugins/chameleon/icons/actions/icon_Layout_16px.svg
- tests/styleplugins/chameleon/icons/theme-icons.qrc
Styleplugin's unit tests need icon_Layout icon file. This file is provided by builtiniconengine test, now it's removed. Add this resource to styleplugin itself.
Log: fix unit tests resource lacking
> tests: fix unit tests resource lacking

- iconengineplugins/diconengine/diconengine.json
- iconengineplugins/diconengine/main.cpp
- platformthemeplugin/qdeepintheme.cpp
iconengine's key is inconsistent with the engine's key returned by the interface create
Log: fix the issue that file manage crashes when dragging and dropping the bookmark
> fix: file manage crash

- styleplugins/chameleon/chameleonstyle.cpp
Orientation field in QStyleOptionProgressBar is removed in Qt6. In Qt5, user may not set state flags, so we still need to judge from orientation.
Log: fix compatibility with orientation
> fix: compatibility with orientation

- debian/control
libfreetype6-dev == > libfreetype-dev
> chore: use libfreetype-dev instead of libfreetype6-dev

- 3rdparty/qdbustrayicon.cpp
Current service name is {domain}.{appName}.kdbus-{dbusConnectionName}. The service name will be duplicated because the app always gets the same dbusConnecionName. So we should add instanceId back. Like this: {domain}.{appName}.kdbus-{dbusConnectionName}-{instanceId}.
Log:
> fix: App failed to create multiple system trays

- 3rdparty/qdbustrayicon.cpp
Current service name is {domain}.{appName}.kdbus-{dbusConnectionName}-{instanceId}. The Service name will fail to register if the {appName} is in chinese. So we change the format to:
org.kde.StatusNotifierItem-{dbusConnectionName}-{instanceId}.
Log:
> fix: some apps failed to create system tray

- styleplugins/chameleon/chameleonstyle.cpp
- styleplugins/chameleon/chameleonstyle.h
- 默认显示滚动条，无滚动时启动隐藏动画
- 鼠标掠过滚动条所在（整个）区域，立即显示滚动条，移开启动隐藏动画
- 鼠标悬停，按下滚动条，滚动条一直显示
- 发生滚动时滚动条立即显示
docs:473QyXLRvOSZ7r3w
> feat: scrollbar show policy tweak

- debian/changelog
> chore: bump version to 5.6.17

- styleplugins/chameleon/chameleonstyle.cpp
- styleplugins/chameleon/resources.qrc
This issue will occur when the application uses QApplication instead of
QGuiApplication in deepin desktop environment.
`libqdeepin.so` cause `libchameleon.so` will be loaded because
QDeepinTheme::themeHint point `chameleon` style, and chameleon plugin
use `chameleon` resource prefix.
QQuickStyleSpec::findStyle in qquickstyle.cpp will find style in
resource path because of `QDir::entryList`, and it causes `style`
is changed to `:/chameleon`, so Chameleon can't be loaded.
Control's style will fallback to Basic style.
Log: chameleon含有`/chameleon`前缀的资源，导致qml对应的Chameleon加载失败
Issue: https://github.com/linuxdeepin/dtk/issues/11
> fix: App can't load qml-module-chameleton plugin

- styleplugins/chameleon/chameleonstyle.cpp
use qapitrace to open apitrace tracking result,
crashes at typeid.
Log:
> fix: qapitrace open file crash

- styleplugins/chameleon/chameleonstyle.cpp
DApplicationHelper is totally dropped in dtk6. Just remove this header inclusion cause it's not used.
Log: remove unused dropped header
> fix: remove unused dropped header

- imageformatplugins/dci/qdciiohandler.cpp
QImageReader::setDecideFormatFromContent(bool ignored) If ignored is set to true, QDciPlugin::create will get empty format.
> fix: dci cannot read when setDecideFormatFromContent

- platformthemeplugin/qdeepintheme.cpp
onFontChanged will send ApplicationFontChange event to all windows. we stop this opration if qApp set a font
dtk菜单显示了就无效了原因如下：
sub menu ==> draw arrow icon ==> QIcon::fromtheme ==> QIconLoader ==> themeHint(SystemIconThemeName) ==> appTheme() ==> connect ==> fontNameChanged
子菜单需要绘制右箭头图标，用了 `QIcon::fromtheme` 。其实只要那个信号槽连上了就会强制更新。
Issue: https://github.com/linuxdeepin/dtk/issues/124
> fix: qApp set fixed font not work

- styleplugins/chameleon/chameleonstyle.cpp
This reverts commit b80e65a4f15d3b505324c0daf2acde6a76efceb6. treeview select state paint error (e.g. deepin-system-monitor, deepin-devicemanager)
> Revert "fix: qapitrace open file crash"

- platformthemeplugin/qdeepintheme.cpp
add version control to ButtonPressKeys
Log: ButtonPressKeys is only supported in Qt6
> chore: ButtonPressKeys is only supported in Qt6

- styleplugins/chameleon/chameleonstyle.cpp
change the icon size of the selected item in the menu according to the suggestion from the designer
Issue: https://github.com/linuxdeepin/developer-center/issues/7446
> fix: icon size of the selected item in context menu

- styleplugins/chameleon/chameleonstyle.cpp
按设计要求,滚动条需要内外边界,且深色模式的颜色是带透明度的黑
Task: https://pms.uniontech.com/task-view-331783.html
> chore: scrollerbar tweak

- styleplugins/chameleon/chameleonstyle.cpp
If only text is displayed in PopupDelay mode and there is a menu, the text and arrows will be centered as a whole
Issue: https://github.com/linuxdeepin/developer-center/issues/7402
> fix: The month button arrow in DCalendarWidget is out of range

- platformthemeplugin/qdeepinfiledialoghelper.cpp
In linglong container, application couldn't find binary `dde-desktop`,
and `com.deepin.filemanager.filedialog` may not be activated.
So we use the `D-Bus Activation` mechanism to activate this service.
Issue: https://github.com/linuxdeepin/developer-center/issues/8433
> fix: try to activate dialog service before init manager

- styleplugins/chameleon/chameleonstyle.cpp
remove _d_dtk_lineeditActionWidth property
Issue: https://github.com/linuxdeepin/developer-center/issues/8423
Issue: https://github.com/linuxdeepin/developer-center/issues/4993
> fix: close action in lineedit is narrowed

- styleplugins/chameleon/chameleonstyle.cpp
Menu's background always fill a color even it's transparent. in somecase we need fill background by caller.
> fix: can't set transparent for Menu's background

- styleplugins/chameleon/chameleonstyle.cpp
- styleplugins/chameleon/chameleonstyle.h
Add a ChameleonAnimation class for the geometry translate animation.
> feat: add animation for menu's selected backgroud

- styleplugins/chameleon/CMakeLists.txt
- styleplugins/chameleon/chameleonstyle.cpp
- styleplugins/chameleon/menu_shadow.svg
- styleplugins/chameleon/resources.qrc
add round and remove shadow for menu item
Log:
> chore: add round and remove shadow for menu item

- styleplugins/chameleon/chameleonstyle.cpp
- styleplugins/chameleon/chameleonstyle.h
更改checkbox和radio实现方式为dci图标,增加动效
Log:
> chore: 更改checkbox和radio实现方式为dci图标,增加动效

- styleplugins/chameleon/chameleonstyle.cpp
> fix: adjust progressbar color

- styleplugins/chameleon/chameleonstyle.cpp
[chore: 调整菜单样式](https://gerrit.uniontech.com/c/qt5integration/+/255954)
[chore: 调整滑动条横条和刻度颜色](https://gerrit.uniontech.com/c/qt5integration/+/255190)
Log:
> menu item and slider style tweak

- styleplugins/chameleon/chameleonstyle.cpp
动效增加开关,通过DGuiApplication::testAttribute(DGuiApplication::HasAnimations)接口和环境变量DTK_DISABLE_ANIMATION_***控制动效总开关和单个动效开关
Log: 动效增加开关
> feat: 动效增加开关

- platformthemeplugin/qdeepintheme.cpp
DPlatformTheme::font() is async call in treeland and will fallback to `QGenericUnixTheme::font` which resolveMask is `FamiliesResolved|SizeResolved`
defaultSystemFontName: Sans Serif (FamiliesResolved) defaultSystemFontSize: 9 (SizeResolved)
Remove the resolveMask to reset font on font changed
> fix: treeland font init failed

- styleplugins/chameleon/chameleonstyle.cpp
Add antialiased for painter.
Fix MenuItem's HMargin implementation, Remove the margin of MenuItem's width instead of the margin of PM_MenuHMargin, otherwise, it caused incorrrect suMenu overlap.
pms: BUG-297003
> fix: missing antialiased for menuItem

- CMakeLists.txt
to be consistent with other dtk projects.
> chore: disable ut by default

- iconengineplugins/svgiconengine/qsvgiconengine.cpp
1. Added QFileInfo check for SVG file existence and lastModified
validity before cache processing
2. Moved svgFileInfo creation outside conditional block for reuse
3. Ensures cache invalidation properly checks file modification times
4. Prevents potential cache issues with invalid file timestamps
fix: 改进SVG图标缓存验证
1. 在缓存处理前添加对SVG文件存在性和最后修改时间的QFileInfo检查
2. 将svgFileInfo创建移到条件块外以便重用
3. 确保缓存失效时正确检查文件修改时间
4. 防止因无效文件时间戳导致的潜在缓存问题
> fix: improve SVG icon cache validation

- debian/rules
1. Added security hardening compiler and linker flags to debian/rules
2. Enabled stack protection, RELRO, immediate binding, and NX
protections
3. These changes improve binary security against common exploit
techniques
4. Follows Debian hardening best practices for package builds
fix: 在构建过程中添加安全加固标志
1. 在 debian/rules 中添加了安全加固的编译器和链接器标志
2. 启用了栈保护、RELRO、立即绑定和NX保护
3. 这些更改提高了二进制文件对常见漏洞利用技术的防护能力
4. 遵循 Debian 软件包构建的安全加固最佳实践
> fix: add security hardening flags to build process

- iconengineplugins/svgiconengine/qsvgiconengine.cpp
Removed the [[maybe_unused]] attribute from the QtConcurrent::run result
variable and replaced it with Q_UNUSED macro. This change was made
because:
1. [[maybe_unused]] is a C++17 feature that might not be supported in
all build environments
2. Q_UNUSED is the Qt-specific and more portable way to suppress unused
variable warnings
3. Maintains consistency with Qt coding standards
4. The variable is intentionally unused as we're running the task
asynchronously without tracking the result
fix: 移除 maybe_unused 属性并添加 Q_UNUSED
移除了 QtConcurrent::run 结果变量的 [[maybe_unused]] 属性，改用 Q_UNUSED
宏。此变更的原因是：
1. [[maybe_unused]] 是 C++17 特性，可能在某些构建环境中不受支持
2. Q_UNUSED 是 Qt 特有的更便携的方式来抑制未使用变量警告
3. 保持与 Qt 编码标准的一致性
4. 该变量是故意不使用的，因为我们异步运行任务而不跟踪结果
> fix: remove maybe_unused attribute and add Q_UNUSED
