platformthemeplugin/qdeepintheme.cpp
platformthemeplugin/qt5deepintheme-plugin.pro
platformthemeplugin/xdgiconenginecreator.cpp
platformthemeplugin/xdgiconenginecreator.h

fix: build failed on Qt 5.7.x

---

platformthemeplugin/dthemesettings.cpp
platformthemeplugin/dthemesettings.h
platformthemeplugin/qdeepintheme.cpp

支持窗口缩放比改变时自动更新其大小，包括窗口从一个屏幕移动到另一个屏幕时

feat: support auto update the window geometry by new device pixel ratio

---

platformthemeplugin/qdeepintheme.cpp

fix: clean warning message of QMetaObject
只在确保开启了针对多个屏幕分别设置了不同缩放比时才窗口所在屏幕改变时开启自动缩放窗口大小的功能。

fix: enable real-time scale for window only on enable screenScaleFactors

---

platformthemeplugin/qdeepintheme.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1373
修复插入一个新屏幕后Qt应用字体变小

fix: font pixel changed when connect a screen

---

styleplugins/dstyleplugin/config.tests/dtkwidget/main.cpp

Move to new API, build passes.

Fix dstyleplugin config tests

---

platformthemeplugin/qdeepintheme.cpp

Fix build with Qt 5.14

---

styleplugins/chameleon/chameleonstyle.cpp
styles/widgetgallery.cpp
styles/widgetgallery.h

根据设计图微调dtoolbutton的样式
Log: 微调dtoolbutton的样式
Bug: https://pms.uniontech.com/task-view-145803.html
Influence: dtoolbutton样式
Change-Id: Iaea678c54c2c8ec5f49113ede2b274f23489a3fd

fix: 带菜单的 dtoolbutton 下拉箭头的微调

---

LICENSE

change LICENSE from GPL-v3 to LGPL-v3+
Log: none

change LICENSE from GPL-v3 to LGPL-v3+

---

.reuse/dep5

fix license check failed
Log: none

chore: update de5

---

.reuse/dep5

*.conf
Log: none
Influence: reuse lint
Change-Id: I1db793d7a3442d859c1668fb9e3ed8d1638138e3

chore: fix license check failed

---

iconengineplugins/dciiconengine/dciiconengine.cpp
iconengineplugins/dciiconengine/dciiconengine.h
iconengineplugins/xdgiconproxyengine/main.cpp
platformthemeplugin/diconproxyengine.cpp
platformthemeplugin/diconproxyengine.h
platformthemeplugin/qdeepintheme.cpp

1. DDIconProxyEngine to proxy iconEngine
2. dciiconengine update icon when themenamechanged
Log: none
Influence: icon theme name changed
Change-Id: I543e3dec21015cb159873c95ba08d2d6b7f0cdef

fix: icon not changed when icon theme name changed

---

platformthemeplugin/qdeepinfiledialoghelper.cpp

Log: 避免硬编码查找路径，提高可移植性
https://github.com/linuxdeepin/developer-center/issues/3374

chore: don't hardcode /usr/bin path

---

iconengineplugins/diconproxyengine/diconproxyengine.cpp
iconengineplugins/diconproxyengine/diconproxyengine.h
iconengineplugins/diconproxyengine/diconproxyengine.json
iconengineplugins/diconproxyengine/diconproxyengine.pro
iconengineplugins/diconproxyengine/main.cpp
iconengineplugins/iconengines.pro
platformthemeplugin/qdeepintheme.cpp
platformthemeplugin/qt5deepintheme-plugin.pro

diconproxyengine read/write not matched
Bug: https://pms.uniontech.com/bug-view-181401.html
Influence: listview moveable item
Log: fix dragging item crashed
Change-Id: I26eb4cdd7873f65081fe4800fce61bc1f9d565d7

fix: listview dragging item crashed

---

tests/iconengines/dciiconengine/ut_dciiconengine.cpp

fix ut failed
[  FAILED  ] ut_DDciIconEngine.key
[  FAILED  ] ut_DDciIconEngine.read
[  FAILED  ] ut_DDciIconEngine.write
Log: fix ut failed
Change-Id: I4db7def62d87bf08c416f38c34a06722de17eef2

fix(build): ut_DDciIconEngine failed

---

styleplugins/chameleon/chameleonstyle.cpp

Issue: https://github.com/linuxdeepin/dtkwidget/issues/388
Bug:https://pms.uniontech.com/bug-view-190119.html

fix: lineedit invisible in translucent window

---

3rdparty/qdbusmenuconnection.cpp
3rdparty/qdbusmenuconnection_p.h
3rdparty/qdbustrayicon.cpp
3rdparty/qdbustrayicon_p.h
3rdparty/qstatusnotifieritemadaptor.cpp
3rdparty/qstatusnotifieritemadaptor_p.h
LICENSES/LicenseRef-Qt-Commercial.txt
platformthemeplugin/qdeepintheme.cpp
platformthemeplugin/qdeepintheme.h
platformthemeplugin/qt5deepintheme-plugin.pro

close linuxdeepin/developer-center#3649

fix: 玲珑应用托盘无法共存

---

platformthemeplugin/qdeepintheme.cpp

use thirdparty::dLcTray instead

fix(build): ‘qLcTray’ was not declared

---

iconengineplugins/dciiconengine/dciiconengine.cpp

由于 dci 图标引擎没有缓存图标,绘制是多次请求图标时
每次都是读取资源获取 dci 图标资源里面的 webp 转成 qimage
webp 转 qimage 比较耗时
Issue: https://github.com/linuxdeepin/developer-center/issues/4122

fix: dci iconEngine not cached pixmap

---

platformthemeplugin/qdeepinfiledialoghelper.cpp

原来默认显示后设置 WM_TRANSIENT_FOR 属性。
在某些情况下（如窗口还未显示）失败或者被桌面覆盖了。
增加一个窗口激活后再次确认该属性
修改 connect 的类型，防止出现重复连接
Issue: https://github.com/linuxdeepin/dtk/issues/65

fix: file dialog Transient_For property

---

CMakeLists.txt
platformthemeplugin/CMakeLists.txt
platformthemeplugin/dthemesettings.cpp
platformthemeplugin/main.cpp
platformthemeplugin/qdeepinfiledialoghelper.cpp
platformthemeplugin/qdeepintheme.cpp
platformthemeplugin/qdeepintheme.h

platformthemeplugin now supports building under Qt6 and using cmake
Log: platform theme plugin supports cmake and Qt6

feat: platformthemeplugin supports cmake and Qt6

---

styles/CMakeLists.txt
styles/widgetgallery.cpp

* Rename styles output bin to gallery;
* Redirect gallery to CMAKE_BINARY_DIR to load plugins correctly;
* Fix wrong display of initial styleplugin.
Log: fix styles output and styleplugin initial display name

fix: redirect styles output

---

iconengineplugins/diconengine/main.cpp
platformthemeplugin/qdeepintheme.cpp

fix the wrong key of diconengine and typos
Log: fix the issue that diconengine load failed

fix: diconengine load failed

---

archlinux/PKGBUILD

It's not used in this project now.

fix: remove unused option in PKGBUILD

---

debian/changelog

chore: bump version to 5.6.20

---

platformthemeplugin/qdeepintheme.cpp

add the keys Return/Enter support in deepintheme
Issue: https://github.com/linuxdeepin/developer-center/issues/5852

fix: Button can't reponse Return/Enter key

---

styleplugins/chameleon/chameleonstyle.cpp

Arrow and Text is incomplete display.
Issue: https://github.com/linuxdeepin/developer-center/issues/1765

fix: wrong style for ComboBox in RightToLeft layout

---

styleplugins/chameleon/chameleonstyle.cpp
styleplugins/chameleon/chameleonstyle.h

1. 更新滚动条样式,适配动画
2.  修复进度条圆角问题以及当进度为1时进度滑块未在进度槽中的问题
Log:

 chore: 更新滚动条样式,适配动画

---

styleplugins/chameleon/chameleonstyle.cpp
styleplugins/chameleon/chameleonstyle.h

checkbox和radio有框选区和文字区,应该只对框选区事件做处理
Log:

fix: 修复在选中框之外hover 和点击也有动画的问题

---

styleplugins/chameleon/CMakeLists.txt
styleplugins/chameleon/chameleonstyle.cpp
styleplugins/chameleon/chameleonstyle.h
styleplugins/chameleon/menu_shadow.svg
styleplugins/chameleon/resources.qrc

merge dev/animation to master
Log:

merge dev/animation to master

---

styleplugins/chameleon/chameleonstyle.cpp

add a switch to menu animation
Log:

chore: add a switch to menu animation

---

3rdparty/qdbustrayicon.cpp

it effects when dbus can't work.
pms: BUG-368399

chore: delay to access dbus for trayicon
